### ISSUE TITLE
Ripple animations not working

### ISSUE THREAD

**Issue by jimlears** [gpbl/material-ui-sass#17]
NOTE: not working on chrome or safari, using autoprefixer, v0.4.1

didn't dig too much, but it looks like the mui-touch-circle div isn't getting injected into the DOM

**Comment by gpbl** [comment]
@jimlears i do see ripple animations using material-ui v0.4.1 with material-ui-sass 0.4.1. 
Are you sure you are using v0.4.1 for both? 
An update to 0.5 is in progress, so maybe it will solve the issue.

**Comment by jimlears** [comment]
animations are working now after upgrading to 0.5.0
