### ISSUE TITLE
postinstall doesn't work as expected 

### ISSUE THREAD

**Issue by SiarheiMelnik** [gpbl/material-ui-sass#18]
My system is ubuntu.
I see err:
> material-ui-sass@0.0.1 postinstall /home/user/project/ipln-ngen/node_modules/material-ui-sass
> cd node_modules/material-ui && npm install && cd docs && npm install

> sh: 1: cd: can't cd to node_modules/material-ui

**Comment by gpbl** [comment]
@SiarheiMelnik are you using the version on master? That should have been fixed. 

Remember: if you just need to use the .scss files, you don't need to run `npm install` – which is required to start the material-ui example, *for developing purpose*. To use the .scss files, just copy the `material-ui` folder in your project.

**Comment by gpbl** [comment]
Closing this since i removed the postinstall cript
