### ISSUE TITLE
Can't override custom variables

### ISSUE THREAD

**Issue by deser** [gpbl/material-ui-sass#22]
Hello! Please add !default in _custom-variables.scss file here:
//App Colors
$primary-1-color: $cyan-500;
$primary-2-color: $cyan-700;
$primary-3-color: $cyan-100;
$accent-1-color: $pink-A200;
$accent-2-color: $pink-A400;
$accent-3-color: $pink-A100;

I expect it will be $primary-1-color: $cyan-500 !default; instead of $primary-1-color: $cyan-500;

Thanks a lot!

**Comment by gpbl** [comment]
Thanks, nice catch!

**Comment by deser** [comment]
Good job! :)
