### ISSUE TITLE
Inout has incompatible margin-top and placeholder 'top'

### ISSUE THREAD

**Issue by deser** [gpbl/material-ui-sass#23]
https://monosnap.com/image/ntOzZkaFffQUeuzGyqOIJIxDcNaT2j
Therefore placeholder is drawn over other elements

**Comment by gpbl** [comment]
This is the same as the [original less file](https://github.com/callemall/material-ui/blob/master/src/less/components/input.less) and it's working well in the [demo](http://material-ui.com/#/components/inputs). Are you sure there are not other styles interfering with it?

**Comment by deser** [comment]
I am sure :). Ok I think this question is for material-ui. Thanks!
