### ISSUE TITLE
Add libsass support

### ISSUE THREAD

**Issue by msikma** [gpbl/material-ui-sass#27]
There are a few minor things that prevent me from building the framework right now. I've made some changes [in my libsass-compatibility](https://github.com/msikma/material-ui-sass/tree/libsass-compatibility) branch that permit me to build the framework, but they haven't been tested really extensively and I'm new to material-ui so I'm probably not the person to do that.

As you can see from [the diff](https://github.com/msikma/material-ui-sass/commit/56069d5ad1e52b607e9c373c6bf5da10e415d4eb), libsass appears to choke on the ripple transition effects. So I've split them up, one for the keyframes and one for the animation value.

I've not made a pull request yet because I'd like to get some feedback on my changes first, since I'm not 100% sure about then.

I've been able to build this using node-sass 1.2.3 which uses libsass 3.1.0.

**Comment by gpbl** [comment]
Thanks @msikma for pointing out this. 

I'm also not happy with ruby-sass, yet it was the choice of the original project so I kept it. I'd love to skip the gulp tasks and just use webpack (which is a good reason for me to switch to node-sass).

If I read the diff well, the problem is nesting transitions mixins into selectors. Your change should be compatible with ruby-sass as well (i believe it's just a matter of code readability), but I'd like to give a try first. Did you try to see if it works with the docs project and gulp?

**Comment by msikma** [comment]
> If I read the diff well, the problem is nesting transitions mixins into selectors.

Yeah, I did some tests in [Sassmeister](http://sassmeister.com/). If you put [this SCSS](https://gist.github.com/msikma/5a7f6b4bf711e8cefd77) in Sassmeister and switch between different engines, you can see that the output changes. Ruby Sass has different output than Libsass, it actually automatically takes the `@keyframes` declaration out of the `a` selector.

I fixed this not because Libsass complained about not being able to compile it, but because the compiled CSS wasn't being accepted as valid by Webpack's CSS loader :)

> Did you try to see if it works with the docs project and gulp?

Haven't done it just yet because I did this real quickly as I was going out, but I'll see if I can do it tomorrow or possibly tonight.

**Comment by gpbl** [comment]
Well AFAIK keyframes shouldn't stay inside selectors, so here ruby-sass is too permissive... now I understand better, thanks!! I'm sure the change wouldn't affect people using ruby-sass. You don't need to check that for me, just send the PR ;-)

I hope we will get rid of those preprocessors soon...!

**Comment by msikma** [comment]
I've made the PR :)

**Comment by gpbl** [comment]
The v0.7.1 now uses lib-sass. thanks @msikma !
