### ISSUE TITLE
out of sync with material-ui less version

### ISSUE THREAD

**Issue by ezmiller** [gpbl/material-ui-sass#30]
This package is not in sync with the less version. I think it would be nice if there were a warning in the Readme. I just switched over to discover this problem. My own fault for doing so so hastily, but nonetheless.

**Comment by ezmiller** [comment]
Also, I forked this project and am going to bring in the styles for some of the features that seem to be missing, such as the text field. Any guidelines for bringing things in from less that might make this a bit easier?

**Comment by titus88** [comment]
+1

**Comment by gpbl** [comment]
@ezmiller and others I'm sorry for the problems you had – I'm in an infortunate situation with a very bad internet connection (worst nightmare ever :-) causing big delays on this project. 

Anyway, I've updated the README with [some more info](https://github.com/gpbl/material-ui-sass#development) about the way I'm converting from Less to Sass. The tedious work has been already done with the first release: now is just about to keep the .scss files updated with the last version. For migrating to v.0.7.0 very few has been changed (we just moved to libsass). I'd start from checking the [changed files](https://github.com/callemall/material-ui/compare/v0.5.0...v0.7.0) and apply the differences.

If you need more help I'll be happy to support you: I've just opened a [gitter chat](https://gitter.im/gpbl/material-ui-sass). If people are starting contributing to the project, we may add a todo list to the [migration issue](https://github.com/gpbl/material-ui-sass/issues/24).

**Comment by gpbl** [comment]
I should add that material-ui is doing [great progress](https://github.com/callemall/material-ui/issues/30#issuecomment-73271729) on the css-in-js branch for removing the less dependency.

**Comment by ezmiller** [comment]
hi @gpbl thanks for responding. i ended up moving away from material-ui. i'm trying to build a fairly stable application using react, and the potential of a future change toward css-in-js seemed such a possibly radical change that i opted to write my own components. i'm enjoying that actually and learning a lot about React in the process.

**Comment by gpbl** [comment]
We made it! Thanks to @janmyler's help, the updated version is now on npm.

@ezmiller see you the next time, then: have fun with React :-)
