### ISSUE TITLE
Should work when installed with npm (without using git)

### ISSUE THREAD

**Issue by leszekhanusz** [gpbl/material-ui-sass#35]
It fails on npm because it is not a git repo

    leszek@leszek-desktop:~/yo/material-ui-sass/node_modules/material-ui-sass$ npm run setup

    > material-ui-sass@0.7.1 setup /home/leszek/yo/material-ui-sass/node_modules/material-ui-sass 
    > git submodule update && cd less && npm install && cd docs && npm install

    fatal: Not a git repository (or any parent up to mount point /home)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

And also because it is missing folders

    leszek@leszek-desktop:~/yo/material-ui-sass/node_modules/material-ui-sass$ npm run dev

    > material-ui-sass@0.7.1 dev /home/leszek/yo/material-ui-sass/node_modules/material-ui-sass
    > gulp

    fs.js:666
      return binding.readdir(pathModule._makeLong(path));
                     ^
    Error: ENOENT, no such file or directory '/home/leszek/yo/material-ui-sass/node_modules    /material-ui-sass/gulp/tasks'

**Comment by gpbl** [comment]
Hi @leszekhanusz, 

the npm version is not intended for development. Why do you have the need to run the dev version from the npm package?

**Comment by leszekhanusz** [comment]
Hi @gpbl,

I was just trying to test your code. I thought (incorrectly probably) that it was possible to get started quickly by running the commands explained in the readme.
You can close this bug.

**Comment by gpbl** [comment]
Those are for contributing :-) The npm package installs only the .scss sources that you can use in your own sass files, i.e. 

```scss
// myfile.scss in root dir
@import "./node_modules/material-ui/main";
```

maybe I should make it clear in the README...
