### ISSUE TITLE
app.js not found

### ISSUE THREAD

**Issue by leszekhanusz** [gpbl/material-ui-sass#36]
After running `npm run dev`, The generated web page is blank and this is the error in the console:

    "NetworkError: 404 Not Found - http://localhost:3000/app.js"

And a toast is appearing briefly with the following text:

    Compile Error
    Cannot find module 'react-tap-event-plugin'
    from '/home/leszek/yo/material-ui-sass-git/
    material-ui-sass/less/docs/src/app'

**Comment by gpbl** [comment]
@leszekhanusz did you try with a fresh install? It looks like a dependency problem.

```
git clone --recursive https://github.com/gpbl/material-ui-sass.git
cd material-ui-sass

npm install    # will install material-ui-sass dep
npm run setup  # will install material-ui docs and deps
npm run dev    # run the dev environment
```

**Comment by leszekhanusz** [comment]
Yes.

I tried the commands above in a new folder and got the same result.
No obvious error during compilation:
http://en.textsave.org/jz0b

**Comment by gpbl** [comment]
I cannot reproduce it on OS X, npm 2.5.1 and node 0.12.0 – maybe you are using an older version of npm? The missing module is actually specified in the parent's [package.json](https://github.com/callemall/material-ui/blob/03c169188dd10ec2242b7806050781867c0291dd/package.json#L37) as peer dependency.

However in case it is an issue with the material-ui package docs :(

**Comment by leszekhanusz** [comment]
I'm on Ubuntu 14.10 with the `chris-lea` node ppa
node v0.10.37
npm 1.4.28

**Comment by leszekhanusz** [comment]
Hmm the package.json file of material-ui is not there because material-ui is not a dependency ....
Works after doing npm install material-ui in the material-ui-sass folder.

**Comment by leszekhanusz** [comment]
material-ui is probably installed globally on your side.

**Comment by gpbl** [comment]
Installing material-ui in material-ui-sass is an half fix since it does not install the docs required to run the demo app (that's why we are using the submodule). Anyway, glad you could fix it :-)
