### ISSUE TITLE
DatePicker is broken

### ISSUE THREAD

**Issue by ashwinputhige** [gpbl/material-ui-sass#38]
Followed the instructions in ReadMe to clone, npm install and run. DatePicker doesn't work. Fails with "Uncaught TypeError: Cannot read property '_currentElement' of null"

**Comment by janmyler** [comment]
I had the same thing, I resolved it by explicitly running `npm install` in `./less` directory.

**Comment by gpbl** [comment]
@ashwinputhige do you still have this problem?

**Comment by ashwinputhige** [comment]
@gpbl Sorry, I am not using this anymore, so I cannot confirm if this problem exists or not.

**Comment by gpbl** [comment]
no problem :)
